name: Main

on: [push, pull_request, workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t mcappy/docker-react -f Dockerfile.dev .
    - name: Run the test cases
      run: docker run -e CI=true mcappy/docker-react yarn test
